### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by Txuritan** [ionsys/storyarchive#2]
### TODO
  - [ ] (Fix imports so it'll make all themes instead of just theme__light--blue (static/less/themes/_theme.less))[#1]
    - [ ] Pages
      - [ ] Make a landing page
      - [ ] Login/logout (Auth0)
      - [ ] Profile page
      - [ ] /community/
        - [ ] Community page
      - [ ] /forum/
        - [ ] Forum page
        - [ ] Thread page
      - [ ] /story/
        - [X] Story page
    - [ ] Components
      - [X] Panel
      - [X] Selector
      - [X] Navbar
      - [ ] Tabs
      - [ ] Button
        - [ ] Dropdown
      - [ ] Pagination
      - [ ] Progressbar
      - [ ] Checkbox
